SETTINGS:
  STARTING_LEVEL: 18
  IS_TRUE_RANDOM_PIECES: False
  WEIGHTS_FILENAME: 'weights_sample_8f'

TRAINING:
  EPISODES: 3000
  EPISODE_INTERVAL: 50
  EPSILON_LIMIT: 2000
  SAVE_SEPARATE_TRAINING_INTERVALS: True

BEHAVIOR:
  IS_DAS_ON: False
  IS_ONE_DIRECTION_MOVEMENT: False 
